---

AllCops:
  DisabledByDefault: true

  Exclude:
    - spec/rails/**/*

  Include:
    - "**/*.rake"
    - "**/Gemfile"
    - "**/Rakefile"

  DisplayCopNames: true

  StyleGuideCopsOnly: false

Style/TrailingWhitespace:
  Enabled: true
