---

AllCops:
  DisabledByDefault: true

  Exclude:
    - spec/rails/**/*
    - gemfiles/vendor/bundle/**/*

  Include:
    - "**/*.rake"
    - "**/Gemfile"
    - "gemfiles/*.gemfile"
    - "**/Rakefile"

  DisplayCopNames: true

  StyleGuideCopsOnly: false

Style/HashSyntax:
  Enabled: true

Style/PredicateName:
  Enabled: true

  NamePrefixBlacklist:
    - is_
    - have_

  NameWhitelist:
    - has_many
    - has_many_actions

Style/TrailingWhitespace:
  Enabled: true

Style/SpaceAfterComma:
  Enabled: true

Style/SpaceInsideParens:
  Enabled: true
