language: ruby
script:
  - time bundle exec rake setup
  - time bundle exec rake test_with_coveralls
install:
  - time gem install bundler # use the very latest bundler
  - time bundle install --without development
rvm:
  - 1.9.3
  - 2.1.1
env:
  - RAILS=3.2.18
  - RAILS=4.1.1
notifications:
  irc:
    channels:
      - "irc.freenode.org#activeadmin"
    on_success: change
    on_failure: always
    skip_join: true
    template:
      - "(%{branch}/%{commit} by %{author}): %{message} (%{build_url})"
