language: ruby
script: time bundle exec rake test_with_coveralls
before_install:
  - date
  - gem install bundler # use the latest bundler, since Travis doesn't update for us
after_install:
  - date
rvm:
  - 1.9.3
  - 2.1.1
env:
  - RAILS=3.2.17
  - RAILS=4.1.0
notifications:
  irc:
    channels:
      - "irc.freenode.org#activeadmin"
    on_success: change
    on_failure: always
    skip_join: true
    template:
      - "(%{branch}/%{commit} by %{author}): %{message} (%{build_url})"
