---

codecov:
  notify:
    require_ci_to_pass: true

comment: off

coverage:
  precision: 1

  range:
    - 70.0
    - 100.0

  round: up

  status:
    changes: false
    patch: true
    project: true
